name: SWAN CI/CD pipeline

on: 
  workflow_dispatch:
    inputs:
      package:
        description: 'Package Name'
        required: true
      version:
        description: 'Package Version'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: master

    - name: Update package version
      run: |
        PKG_NAME_LOWER=$(echo " ${{ inputs.package }}" | tr '[:upper:]' '[:lower:]')
        PKG_VER=$(echo "${{ inputs.version }}" | sed -e "s/v//g")
        sed -i "s/\( $PKG_NAME_LOWER==*\)[^ ]*/\1$PKG_VER/" Dockerfile

    - name: Create pull request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH="${{ inputs.package }}-${{ inputs.version }}"
        MESSAGE="Updated package ${{ inputs.package }} to version ${{ inputs.version }}"

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b "$BRANCH"
        git add Dockerfile
        git commit -m "$MESSAGE"
        git push origin "$BRANCH"
        gh pr create --title "$MESSAGE" --body "" --head "$BRANCH" --base master
